version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/.github"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
  - package-ecosystem: gradle
    directory: "/jackett-rss-processor-service"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    ignore:
      - dependency-name: "com.sun.xml.bind:*"

  - package-ecosystem: npm
    directory: "/jackett-rss-processor-frontend"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
