version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
  - package-ecosystem: gradle
    directory: "/backend"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "/webapp"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
