spring:
  application:
    name: jackett-rss-process

application:
  blackHole: "/tmp"
  max-results: 10
  sync-delay: 300000
  local-cache: 1

logging:
  level:
    org:
      springframework:
        cache: TRACE

---
spring:
  profiles: production

application:
  blackHole: "/watched"
  max-results: 100
  local-cache: 5
