version: '3.7'
services:

  jackett-rss-mongo:
    image: mongo:latest
    container_name: jackett-rss-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    logging:
      options:
        max-size: "2m"
        max-file: "5"

volumes:
  mongo-data:
