version: '3.7'
services:

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    logging:
      options:
        max-size: "2m"
        max-file: "5"

  jackett-rss-processor:
    image: peavers/jackett-rss-processor:latest
    container_name: jackett-rss-processor
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ${WATCH_DIRECTORY}:/watched
    depends_on:
      - jackett
      - jackett-rss-mongo
    logging:
      options:
        max-size: "2m"
        max-file: "5"

  jackett-rss-mongo:
    image: mongo:latest
    container_name: jackett-rss-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    logging:
      options:
        max-size: "2m"
        max-file: "5"

volumes:
  mongo-data:
