spring:
  application:
    name: rss-service

application:
  blackHole: "/tmp"
  max-results: 10
  sync-delay: 300000

logging:
  level:
    org:
      springframework:
        cache: TRACE

---
spring:
  profiles: production

application:
  blackHole: "/watched"
  max-results: 100
