on:
  push:
    paths:
      - 'jackett-rss-processor-ui/**'
  pull_request:
    paths:
      - 'jackett-rss-processor-ui/**'

name: Continuous-integration-ui

jobs:
  check:
    name: Build and analyze
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST: ${{ secrets.SONAR_HOST }}

    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Using Node 14
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 14

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Analyze
        working-directory: ./jackett-rss-processor-ui
        run: |
          npm install
          npm run build
