on:
  push:
    paths:
      - 'jackett-rss-processor-core/**'
  pull_request:
    paths:
      - 'jackett-rss-processor-core/**'

name: Continuous-integration-core

jobs:
  check:
    name: Build and analyze
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST: ${{ secrets.SONAR_HOST }}

    if: ${{ github.actor != 'dependabot[bot]' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Using Java 15
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 15

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.sonar/cache
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Analyze
        run: ./gradlew build sonarqube --info
