on:
  workflow_dispatch:

name: Release new version

jobs:
  create-release:
    runs-on: ubuntu-latest
    name: Release to DockerHub
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Using Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Bump version
        uses: anothrNick/github-tag-action@1.49.0
        env:
          WITH_V: true

      - name: Get new tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 1.0.0

      - name: Build changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3

      - name: Publish
        run: ./gradlew jib

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.previoustag.outputs.tag }}
          release_name: ${{ steps.previoustag.outputs.tag }}
          body: ${{steps.build_changelog.outputs.changelog}}
